// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjzoxyvfxcaoahkzmde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuanpveHl2ZnhjYW9haGt6bWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDQ4ODEsImV4cCI6MjA2MjEyMDg4MX0.qBk0l81Pu8SO2uChjvXNREwsPNIgcmtZnYRbz2eryXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);